In [34]:
import numpy as np

Задание 1. 
Представить фильмы в виде бинарных векторов (numpy array) используюя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

In [35]:
v1 = np.array([0, 0, 1, 0, 1, 0]) #Игра в имитацию
v2 = np.array([0, 1, 1, 1, 0, 0]) #Ярость
v3 = np.array([0, 0, 1, 1, 0, 0]) #12 лет рабства
v4 = np.array([1, 0, 0, 1, 0, 1]) #Однажды в Голливуде

Задание 2.
Вычислить Евклидову норму каждого из векторов, полученных в Задании 1.

In [36]:
np.linalg.norm(v1)

1.4142135623730951

In [37]:
np.linalg.norm(v2)

1.7320508075688772

In [38]:
np.linalg.norm(v3)

1.4142135623730951

In [39]:
np.linalg.norm(v4)

1.7320508075688772

Задание 3.
Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [40]:
np.dot(v2, v3) / (np.linalg.norm(v2) * np.linalg.norm(v3)) #косинус угла между векторами

0.8164965809277259

In [41]:
np.arccos(np.dot(v2, v3) / (np.linalg.norm(v2) * np.linalg.norm(v3))) #arccos

0.6154797086703875

In [42]:
np.rad2deg(np.arccos(np.dot(v2, v3) / (np.linalg.norm(v2) * np.linalg.norm(v3)))) #величина угла в градусах

35.26438968275466

Задание 4.
Объединить векторы, полученные в Задании 1 в матрицу, где каждый вектор является строкой матрицы. Полученную матрицу умножить на вектор [1,2,3,4]

In [43]:
A1 = np.array([[0, 0, 1, 0, 1, 0], [0, 1, 1, 1, 0, 0], [0, 0, 1, 1, 0, 0], [1, 0, 0, 1, 0, 1]])
A1

array([[0, 0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [1, 0, 0, 1, 0, 1]])

In [44]:
v5 = np.array([1, 2, 3, 4])
v5

array([1, 2, 3, 4])

In [45]:
v6 = v5[np.newaxis, :].T #транспонируем вектор
v6

array([[1],
       [2],
       [3],
       [4]])

In [46]:
A1 * v6 #результат умножения

array([[0, 0, 1, 0, 1, 0],
       [0, 2, 2, 2, 0, 0],
       [0, 0, 3, 3, 0, 0],
       [4, 0, 0, 4, 0, 4]])

Задание 5.
Вычислить на бумаге и с помощью Python значение первой и второй производной для функции 3*x*(x**2 + x)**3 в точке x = 1

In [47]:
import sympy as sym

In [48]:
x = sym.Symbol('x')

In [49]:
3*x*(x**2 + x)**3

3*x*(x**2 + x)**3

In [50]:
res = sym.diff((3*x*(x**2 + x)**3), x) #первая производная
res

3*x*(6*x + 3)*(x**2 + x)**2 + 3*(x**2 + x)**3

In [51]:
res.subs(x, 1) #значение первой производной в точке х=1

132

In [52]:
res1 = sym.diff(res, x) #вторая производная
res1

3*x*(4*x + 2)*(6*x + 3)*(x**2 + x) + 18*x*(x**2 + x)**2 + 6*(6*x + 3)*(x**2 + x)**2

In [53]:
res1.subs(x, 1) #значение второй производной в точке х=1

612